Security

diff --git a/04-volume/01-basic/02-hostpath/02-hostpath-cat.yaml b/04-volume/01-basic/02-hostpath/02-hostpath-cat.yaml
--- a/04-volume/01-basic/02-hostpath/02-hostpath-cat.yaml
+++ b/04-volume/01-basic/02-hostpath/02-hostpath-cat.yaml
@@ -5,22 +5,22 @@ metadata:
 spec:
   nodeName: easykube-worker
   containers:
-  - name: watcher
-    image: busybox
-    command:
-      - /bin/sh
-      - -c
-      - |
-        while true; do
-          echo "📂 Contents of /data:"
-          cat /mounted/test.txt || echo "⚠️ Cannot access /data"
-          sleep 5
-        done
-    volumeMounts:
-    - name: host-volume
-      mountPath: /mounted
+    - name: watcher
+      image: busybox:1.35
+      command:
+        - /bin/sh
+        - -c
+        - |
+          while true; do
+            echo "📂 Contents of /data:"
+            cat /mounted/test.txt || echo "⚠️ Cannot access /data"
+            sleep 5
+          done
+      volumeMounts:
+        - name: host-volume
+          mountPath: /mounted
   volumes:
-  - name: host-volume
-    hostPath:
-      path: /tmp/hostpath
-      type: DirectoryOrCreate
+    - name: host-volume
+      hostPath:
+        path: /tmp/hostpath
+        type: DirectoryOrCreate
